[xoConnection]
  url = 'localhost:9000'
  email = 'admin@admin.net'
  password = 'admin'

[vms]
  default = '0342407f-9727-4f12-83c2-9d0c458916c2'

[templates]
  default = '1a33d04d-1a9c-e2af-ae42-010554eed513'

[remotes]
  default = '8565fc53-ea32-40ea-b380-dd1b8f3b5d44'
  nfs = { name = 'NFS_remote_XOTest', url = 'nfs://192.168.100.5:/tank' }
  smb = { name = 'SMB_remote_XOTest', url = 'smb://Administrator:q3oi6d9X8uenGvdLnHk2@WORKGROUP\\\\192.168.100.51\\smb\u0000' }

[srs]
  default = 'a5954951-3dfa-42b8-803f-4bc270b22a0b'
