[xoConnection]
  url = ''
  email = ''
  password = ''

[vms]
  default = ''

[templates]
  default = ''

[remotes]
  default = { name = '', url = '' }
  nfs = { name = '', url = '' }
  smb = { name = '', url = '' }

[srs]
  default = ''
